/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

/// InlineResponse2003 : An catchpoint start response.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse2003 {
    /// Catchup start response string
    #[serde(rename = "catchup-message")]
    pub catchup_message: String,
}

impl InlineResponse2003 {
    /// An catchpoint start response.
    pub fn new(catchup_message: String) -> InlineResponse2003 {
        InlineResponse2003 {
            catchup_message,
        }
    }
}


