/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

/// InlineResponse200 : PendingTransactions is an array of signed transactions exactly as they were submitted.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse200 {
    /// An array of signed transaction objects.
    #[serde(rename = "top-transactions")]
    pub top_transactions: Vec<serde_json::Value>,
    /// Total number of transactions in the pool.
    #[serde(rename = "total-transactions")]
    pub total_transactions: i32,
}

impl InlineResponse200 {
    /// PendingTransactions is an array of signed transactions exactly as they were submitted.
    pub fn new(top_transactions: Vec<serde_json::Value>, total_transactions: i32) -> InlineResponse200 {
        InlineResponse200 {
            top_transactions,
            total_transactions,
        }
    }
}


