/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse2006 {
    /// encoding of the transaction hash.
    #[serde(rename = "txId")]
    pub tx_id: String,
}

impl InlineResponse2006 {
    pub fn new(tx_id: String) -> InlineResponse2006 {
        InlineResponse2006 {
            tx_id,
        }
    }
}


