/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

/// InlineResponse2005 : Supply represents the current supply of MicroAlgos in the system



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse2005 {
    /// Round
    #[serde(rename = "current_round")]
    pub current_round: i32,
    /// OnlineMoney
    #[serde(rename = "online-money")]
    pub online_money: i32,
    /// TotalMoney
    #[serde(rename = "total-money")]
    pub total_money: i32,
}

impl InlineResponse2005 {
    /// Supply represents the current supply of MicroAlgos in the system
    pub fn new(current_round: i32, online_money: i32, total_money: i32) -> InlineResponse2005 {
        InlineResponse2005 {
            current_round,
            online_money,
            total_money,
        }
    }
}


