/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ErrorResponse : An error response with optional data field.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorResponse {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
    #[serde(rename = "message")]
    pub message: String,
}

impl ErrorResponse {
    /// An error response with optional data field.
    pub fn new(message: String) -> ErrorResponse {
        ErrorResponse {
            data: None,
            message,
        }
    }
}


