/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InlineResponse400 {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
    #[serde(rename = "message")]
    pub message: String,
}

impl InlineResponse400 {
    pub fn new(message: String) -> InlineResponse400 {
        InlineResponse400 {
            data: None,
            message,
        }
    }
}


