/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InlineResponse2001 {
    #[serde(rename = "account")]
    pub account: Box<crate::models::Account>,
    /// Round at which the results were computed.
    #[serde(rename = "current-round")]
    pub current_round: i32,
}

impl InlineResponse2001 {
    pub fn new(account: crate::models::Account, current_round: i32) -> InlineResponse2001 {
        InlineResponse2001 {
            account: Box::new(account),
            current_round,
        }
    }
}


