/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InlineResponse20012 {
    #[serde(rename = "balances")]
    pub balances: Vec<crate::models::MiniAssetHolding>,
    /// Round at which the results were computed.
    #[serde(rename = "current-round")]
    pub current_round: i32,
    /// Used for pagination, when making another request provide this token with the next parameter.
    #[serde(rename = "next-token", skip_serializing_if = "Option::is_none")]
    pub next_token: Option<String>,
}

impl InlineResponse20012 {
    pub fn new(balances: Vec<crate::models::MiniAssetHolding>, current_round: i32) -> InlineResponse20012 {
        InlineResponse20012 {
            balances,
            current_round,
            next_token: None,
        }
    }
}


