/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse2006 {
    #[serde(rename = "asset")]
    pub asset: Box<crate::models::Asset>,
    /// Round at which the results were computed.
    #[serde(rename = "current-round")]
    pub current_round: i32,
}

impl InlineResponse2006 {
    pub fn new(asset: crate::models::Asset, current_round: i32) -> InlineResponse2006 {
        InlineResponse2006 {
            asset: Box::new(asset),
            current_round,
        }
    }
}


