/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse2002 {
    /// Round at which the results were computed.
    #[serde(rename = "current-round")]
    pub current_round: i32,
    /// Used for pagination, when making another request provide this token with the next parameter.
    #[serde(rename = "next-token", skip_serializing_if = "Option::is_none")]
    pub next_token: Option<String>,
    #[serde(rename = "transactions")]
    pub transactions: Vec<crate::models::Transaction>,
}

impl InlineResponse2002 {
    pub fn new(current_round: i32, transactions: Vec<crate::models::Transaction>) -> InlineResponse2002 {
        InlineResponse2002 {
            current_round,
            next_token: None,
            transactions,
        }
    }
}


