/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InlineResponse20015 {
    /// Round at which the results were computed.
    #[serde(rename = "current-round")]
    pub current_round: i32,
    #[serde(rename = "transaction")]
    pub transaction: Box<crate::models::Transaction>,
}

impl InlineResponse20015 {
    pub fn new(current_round: i32, transaction: crate::models::Transaction) -> InlineResponse20015 {
        InlineResponse20015 {
            current_round,
            transaction: Box::new(transaction),
        }
    }
}


